### ISSUE TITLE
Installation fails with `Unable to detect version control system`

### ISSUE THREAD

**Issue by souliane** [ewjoachim/poetry_to_pre_commit#7]
This looks great! I tried it by it fails to install:
```
[INFO] Installing environment for https://github.com/ewjoachim/poetry-to-pre-commit.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/adrien/.cache/pre-commit/repox9p_hs86/py_env-python3.10/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /home/adrien/.cache/pre-commit/repox9p_hs86
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [26 lines of output]
          Traceback (most recent call last):
            File "/home/adrien/.cache/pre-commit/repox9p_hs86/py_env-python3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/home/adrien/.cache/pre-commit/repox9p_hs86/py_env-python3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/home/adrien/.cache/pre-commit/repox9p_hs86/py_env-python3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/tmp/pip-build-env-7c0o866h/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 42, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
            File "/tmp/pip-build-env-7c0o866h/overlay/lib/python3.10/site-packages/poetry_dynamic_versioning/patch.py", line 26, in alt_poetry_create
              name = _get_and_apply_version(
            File "/tmp/pip-build-env-7c0o866h/overlay/lib/python3.10/site-packages/poetry_dynamic_versioning/__init__.py", line 608, in _get_and_apply_version
              version, instance = _get_version(config, name)
            File "/tmp/pip-build-env-7c0o866h/overlay/lib/python3.10/site-packages/poetry_dynamic_versioning/__init__.py", line 452, in _get_version
              version = _get_version_from_dunamai(vcs, pattern, config)
            File "/tmp/pip-build-env-7c0o866h/overlay/lib/python3.10/site-packages/poetry_dynamic_versioning/__init__.py", line 417, in _get_version_from_dunamai
              return Version.from_vcs(
            File "/tmp/pip-build-env-7c0o866h/overlay/lib/python3.10/site-packages/dunamai/__init__.py", line 1946, in from_vcs
              return cls._do_vcs_callback(
            File "/tmp/pip-build-env-7c0o866h/overlay/lib/python3.10/site-packages/dunamai/__init__.py", line 1985, in _do_vcs_callback
              return callback(**kwargs)
            File "/tmp/pip-build-env-7c0o866h/overlay/lib/python3.10/site-packages/dunamai/__init__.py", line 1906, in from_any_vcs
              vcs = _detect_vcs(None, path)
            File "/tmp/pip-build-env-7c0o866h/overlay/lib/python3.10/site-packages/dunamai/__init__.py", line 385, in _detect_vcs
              raise RuntimeError(" ".join(error_parts))
          RuntimeError: Unable to detect version control system. Checked: Git. Not installed: Mercurial, Darcs, Subversion, Bazaar, Fossil, Pijul.
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
Check the log at /home/adrien/.cache/pre-commit/pre-commit.log
[1]    495558 exit 1     git commit -a
```
I don't know how to fix this :-p

**Comment by souliane** [comment]
Workaround:
```
poetry add git+https://github.com/ewjoachim/poetry-to-pre-commit
```
And use the local repo, e.g.:
```
  - repo: local
    hooks:
      - id: sync-repos
        name: sync-repos
        entry: sync-repos
        language: system
      - id: sync-hooks-additional-dependencies
        name: sync-hooks-additional-dependencies
        entry: sync-hooks-additional-dependencies
        args: [--bind, mypy=main]
        language: system
```

**Comment by ewjoachim** [comment]
Strange, it's as if pre-commit had pulled the repo but without .git. I wonder why, and why I didn't reproduce this in the repo I manage where I tested this, [procrastinate](https://results.pre-commit.ci/run/github/170681179/1711975655.ilMZLsDPREeZNASvMKhJFQ)

**Comment by ewjoachim** [comment]
Hm, I wasn't able to reproduce yet. I tried doing it in a docker so my setup is irrelevant, I tried with either `rev: <tag>` or `rev: <commit>`, and no reproduction. I tried seeing if the strict parameter would cause this error, but it causes a different one.

I tried older versions of pre-commit and it worked with 1.0.0 (and I can't imagine you'd have an older version than 1.0.0).

I can't find a setting in pre-commit that would impact how the repository is fetched (especially in a way that would end up with the repo not having `.git`).

I'll need you to share a bit more on your pre-commit config, your setup (computer vs CI) etc.

**Comment by ewjoachim** [comment]
I've tried something in #9 but it's just a hunch. Can you try and tell me if it solves it for you ?

**Comment by souliane** [comment]
I tried and it works with version 2.0.1, but I strangely was not able to reproduce with version 2.0.0 (also after `pre-commit clean`). Something was interfering, but I don't know what.

Sorry :-/ Since pre-commit.com is only for git, I think that #9 does not hurt.

**Comment by ewjoachim** [comment]
Well as long as it works :)
Thanks for taking the time to test.

**Comment by souliane** [comment]
Just FYI, today the issue is here again, also with 2.0.1.
We don't know if this is linked to this project or not, so I don't think that it is necessary to re-open.

**Comment by ewjoachim** [comment]
I'll keep it open in case someone else has the issue too for visibility

**Comment by souliane** [comment]
The apparent randomness and difficulty to reproduce was probably related to the command that I type to trigger the installation. It appears that:
1. when installing directly with pre-commit e.g. `pre-commit run --all-files`, the installation works
2. when installing indirectly via `git commit -a`, it fails.

To reproduce, just `pre-commit clean` before trying one of these 2 commands in a project that has `poetry-to-pre-commit` declared in `.pre-commit-config.yaml`.

Also, I tried with https://github.com/souliane/poetry-to-pre-commit/commit/adef67be8436b81b2e14adb47cb3f653da4b83bc and this seems to fix the issue when doing `git commit -a`. Is there a reason to use `poetry-dynamic-versioning` as build backend or could we switch to `poetry.core.masonry`?

**Comment by ewjoachim** [comment]
> Is there a reason to use poetry-dynamic-versioning as build backend or could we switch to poetry.core.masonry?

[`poetry-dynamic-versioning`](https://pypi.org/project/poetry-dynamic-versioning/) says that's what we're supposed to do. Maybe we could try with https://pypi.org/project/poetry-git-version-plugin/ if it works better?

**Comment by ewjoachim** [comment]
Solved the problem by removing poetry-dynamic-versioning from the equation. Makes releasing slightly harder.

**Comment by souliane** [comment]
Sorry for the late reply... thanks for fixing this!
